name: Docker Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    name: Docker run workflow
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4  # ⬅️ This was missing

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

############################### Java ###############################
      # https://my-spring-boot-app-pzc1.onrender.com
      - name: Build Application docker - 2
        working-directory: ./java/spring_boot_web_apps_gradle/java_applications
        run: |
          
          docker build -t my-spring-boot-app .
          # docker run -p 8080:8080 my-spring-boot-app
          docker tag my-spring-boot-app sreedockerhub19/my-spring-boot-app:latest
          docker push sreedockerhub19/my-spring-boot-app:latest

      - name: Build Application docker - 2.1
        working-directory: ./java/spring_boot_rest_API_app_maven
        run: |
          docker build -t my-spring-boot-maven-app .
          # docker run -p 8080:8080 my-spring-boot-maven-app
          docker tag my-spring-boot-maven-app sreedockerhub19/my-spring-boot-maven-app:latest
          docker push sreedockerhub19/my-spring-boot-maven-app:latest

      # https://my-vertx-app-w215.onrender.com
      - name: Build Application docker - 0
        working-directory: ./java/vertx_
        run: |
          docker build -t my-vertx-app .
          docker tag my-vertx-app sreedockerhub19/my-vertx-app:latest
          docker push sreedockerhub19/my-vertx-app:latest

      # https://my-javalin-app-latest.onrender.com/
      - name: Build Application docker - 6
        working-directory: ./java/javalin_
        run: |
          docker build -t javalin-java-app .
          # docker run -p 8080:8080 javalin-java-app
          docker tag javalin-java-app sreedockerhub19/javalin-java-app:latest
          docker push sreedockerhub19/javalin-java-app:latest

      # https://my-quarkus-java-app.onrender.com
      - name: Build Application docker - 8
        working-directory: ./java/quarkus_
        run: |
          docker build -t my-quarkus-java-app .
          # docker run -p 8080:8080 my-quarkus-java-app
          docker tag my-quarkus-java-app sreedockerhub19/my-quarkus-java-app:latest
          docker push sreedockerhub19/my-quarkus-java-app:latest
